name: BUILD

on:
  push:
    branches:
      - develop
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run lint
        run: |
          npm run lint -- --no-fix

      - name: Run tests
        run: |
          npm run test:unit

      - name: Run circular references check
        run: |
          npm run circular-check

      - name: Build
        run: |
          npm run build

      - name: Upload fluidd.zip
        uses: actions/upload-artifact@v4
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist
